// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/eugenshima/balance/internal/model"

	uuid "github.com/google/uuid"
)

// BalanceService is an autogenerated mock type for the BalanceService type
type BalanceService struct {
	mock.Mock
}

// CreateBalance provides a mock function with given fields: ctx, user
func (_m *BalanceService) CreateBalance(ctx context.Context, user *model.Balance) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Balance) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBalance provides a mock function with given fields: ctx, userID
func (_m *BalanceService) DeleteBalance(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllBalances provides a mock function with given fields: ctx
func (_m *BalanceService) GetAllBalances(ctx context.Context) ([]*model.Balance, error) {
	ret := _m.Called(ctx)

	var r0 []*model.Balance
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Balance); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Balance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *BalanceService) GetUserByID(ctx context.Context, userID uuid.UUID) (*model.Balance, error) {
	ret := _m.Called(ctx, userID)

	var r0 *model.Balance
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Balance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBalance provides a mock function with given fields: ctx, user
func (_m *BalanceService) UpdateBalance(ctx context.Context, user *model.Balance) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Balance) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewBalanceService interface {
	mock.TestingT
	Cleanup(func())
}

// NewBalanceService creates a new instance of BalanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBalanceService(t mockConstructorTestingTNewBalanceService) *BalanceService {
	mock := &BalanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
